name: ebpf
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'update version'     
        required: true
        default: default
env:
  XRAY_DIR: ebpf_bk

permissions: write-all

jobs:
  dmit-us:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y%m%d%H%M')"
        shell: bash
      - name: restore iptables from file
        uses: appleboy/ssh-action@master
        with:
          overwrite: true
          host: ${{ secrets.VPS_HOST_US }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_KEY_US }}
          script: |
              systemctl stop ebpf
              systemctl stop ebpf
              
              rm -rf /root/ebpf
              mkdir -p /root/ebpf/
              wget https://raw.githubusercontent.com/crab21/vps_deploy/main/bin/ebpf -O /root/ebpf/ebpf
              chmod +x /root/ebpf/ebpf

              cat << EOF > /etc/systemd/system/ebpf.service
              [Unit]
              Description=ebpf service
              After=network.target
              [Service]
              User=root
              Group=root
              PermissionsStartOnly=false
              WorkingDirectory=/root/ebpf
              Environment=RUST_LOG=ERROR
              Environment=PATH=/usr/sbin:$PATH
              ExecStart=/root/ebpf/ebpf
              LimitNOFILE=1048576
              LimitNPROC=1048576
              LimitCORE=1048576
              LimitMEMLOCK=10455360
              # TasksMax=1048576
              RestartSec=2s
              [Install]
              WantedBy=multi-user.target
              EOF

              systemctl daemon-reload
              systemctl enable --now ebpf
              systemctl restart ebpf
  dmit-hk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y%m%d%H%M')"
        shell: bash
      - name: restore iptables from file
        uses: appleboy/ssh-action@master
        with:
          overwrite: true
          host: ${{ secrets.VPS_HOST_DMIT_HK }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_KEY_DMIT_HK }}
          script: |
              systemctl stop ebpf
              systemctl stop ebpf
              
              rm -rf /root/ebpf
              mkdir -p /root/ebpf/
              wget https://raw.githubusercontent.com/crab21/vps_deploy/main/bin/ebpf -O /root/ebpf/ebpf
              chmod +x /root/ebpf/ebpf

              cat << EOF > /etc/systemd/system/ebpf.service
              [Unit]
              Description=ebpf service
              After=network.target
              [Service]
              User=root
              Group=root
              PermissionsStartOnly=false
              WorkingDirectory=/root/ebpf
              Environment=RUST_LOG=ERROR
              Environment=PATH=/usr/sbin:$PATH
              ExecStart=/root/ebpf/ebpf
              LimitNOFILE=1048576
              LimitNPROC=1048576
              LimitCORE=1048576
              LimitMEMLOCK=10455360
              # TasksMax=1048576
              RestartSec=2s
              [Install]
              WantedBy=multi-user.target
              EOF

              systemctl daemon-reload
              systemctl enable --now ebpf
              systemctl restart ebpf
  vm-19:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y%m%d%H%M')"
        shell: bash
      - name: restore iptables from file
        uses: appleboy/ssh-action@master
        with:
          overwrite: true
          host: ${{ secrets.VPS_HOST_VMSHELL_19 }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_KEY_VMSHELL_19 }}
          script: |
              systemctl stop ebpf
              systemctl stop ebpf
              
              rm -rf /root/ebpf
              mkdir -p /root/ebpf/
              wget https://raw.githubusercontent.com/crab21/vps_deploy/main/bin/ebpf -O /root/ebpf/ebpf
              chmod +x /root/ebpf/ebpf

              cat << EOF > /etc/systemd/system/ebpf.service
              [Unit]
              Description=ebpf service
              After=network.target
              [Service]
              User=root
              Group=root
              PermissionsStartOnly=false
              WorkingDirectory=/root/ebpf
              Environment=RUST_LOG=ERROR
              Environment=PATH=/usr/sbin:$PATH
              ExecStart=/root/ebpf/ebpf
              LimitNOFILE=1048576
              LimitNPROC=1048576
              LimitCORE=1048576
              LimitMEMLOCK=10455360
              # TasksMax=1048576
              RestartSec=2s
              [Install]
              WantedBy=multi-user.target
              EOF

              systemctl daemon-reload
              systemctl enable --now ebpf
              systemctl restart ebpf
  vm-66:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y%m%d%H%M')"
        shell: bash
      - name: restore iptables from file
        uses: appleboy/ssh-action@master
        with:
          overwrite: true
          host: ${{ secrets.VPS_HOST_VMSHELL_66 }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_KEY_VMSHELL_66 }}
          script: |
              systemctl stop ebpf
              systemctl stop ebpf
              
              rm -rf /root/ebpf
              mkdir -p /root/ebpf/
              wget https://raw.githubusercontent.com/crab21/vps_deploy/main/bin/ebpf -O /root/ebpf/ebpf
              chmod +x /root/ebpf/ebpf

              cat << EOF > /etc/systemd/system/ebpf.service
              [Unit]
              Description=ebpf service
              After=network.target
              [Service]
              User=root
              Group=root
              PermissionsStartOnly=false
              WorkingDirectory=/root/ebpf
              Environment=RUST_LOG=ERROR
              Environment=PATH=/usr/sbin:$PATH
              ExecStart=/root/ebpf/ebpf
              LimitNOFILE=1048576
              LimitNPROC=1048576
              LimitCORE=1048576
              LimitMEMLOCK=10455360
              # TasksMax=1048576
              RestartSec=2s
              [Install]
              WantedBy=multi-user.target
              EOF

              systemctl daemon-reload
              systemctl enable --now ebpf
              systemctl restart ebpf